serve:
	./scripts.sh serve

start:
	./scripts.sh start

build:
	./scripts.sh build

install:
	./scripts.sh install

test:
	./scripts.sh test

deploy:
	FIREBASE_TOKEN=$(FIREBASE_TOKEN) ./scripts.sh deploy