name: Web Frontend CI

on: [push, pull_request]

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'src/web/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: src/web
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: make install

    - name: Install Playwright browsers and dependencies  
      run:  npx playwright install-deps webkit && npx playwright install webkit
      
    - name: E2E tests
      run: make test-e2e

    - name: Unit tests
      run: make test-unit

  # Required status check job for Web branch protection
  web-ci:
    runs-on: ubuntu-24.04
    needs: [test]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate Status
        run:  .github/scripts/evaluate-workflow-status.sh "${{ join(needs.*.result, ' ') }}"

  production-deployment:
    runs-on: ubuntu-24.04
    needs: [web-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.web == 'true'
    steps:
      - name: Clone repository for production build
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node dependencies
        run: make -C src/web install
      - name: Build
        run: make -C src/web build
        env:
          VITE_EXCHANGE_RATES_API_KEY: ${{ secrets.VITE_EXCHANGE_RATES_API_KEY}}
      - name: Deploy to Firebase Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONVERTOR_2B5DD }}
          projectId: convertor-2b5dd
          channelId: live
