name: Web Frontend CI
on:
  push:
    branches: [ main ]
    paths:
      - 'src/web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/web/**'
jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: src/web
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: make install

    - name: Install Playwright browsers and dependencies  
      run:  npx playwright install-deps webkit && npx playwright install webkit
      
    - name: E2E tests
      run: make e2e

    - name: Unit tests
      run: make test

  production-deployment:
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    steps:
      - name: Clone repository for production build
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node dependencies
        run: make -C src/web install
      - name: Build
        run: make -C src/web build
      - name: Deploy to Firebase Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONVERTOR_2B5DD }}
          projectId: convertor-2b5dd
          channelId: live
